# Generated by Django 5.2.4 on 2025-07-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passkeys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passkey",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passkey",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
